# Github action to build the container and push it to GHCR
---
name: Build and push container

on:
  push:
    branches:
      - main

# Allow to push to GHCR
permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
          labels: |
            org.opencontainers.image.title=repo
            org.opencontainers.image.description=repo
            org.opencontainers.image.url=${{ github.repository }}
